### ISSUE TITLE
Contact email

### ISSUE THREAD

**Issue by AndrewRadev** [sanesecurityonline/sanesecurityonline#13]
Би било изключително добре да има мейл, на който да могат хора да ни пращат неща, който да сложим в ЧЗВ, а също и на отделна страница "Контакти". Нямаме коментари, а github issues са удобни само за хора, които имат акаунти в github.

**Comment by kunev** [comment]
Има contact@sanesecurity.online, на който това му беше идеята като го правих, може би е добра идея да направя няколко други. Не съм сигурен как стои въпроса с MX record-и за IDN, за да мога да направя @разумна-сигурно.online адрес, за да няма такива разминавания.

За коментарите съм скептичен, предвид че всичко е просто сервиране на статични файлове. Опитвал съм се да правя грозни комбинации с hugo и [isso](https://github.com/posativ/isso). Не ми харесва вкарването на state в нещата и не знам колко е нужно поне на тоя етап. Отделно нуждата от модерация (не толкова от невъзпитани коментатори, колкото от ботове) е задача, с която не съм сигурен, че има смисъл да се наемаме.

**Comment by AndrewRadev** [comment]
Да, и аз не бих бутал за коментари. Бих сложил може би под всяка статия "ако имате коментари, пращайте ги на този адрес, или пуснете github issue".

**Comment by AndrewRadev** [comment]
Сложих въпросната секция "дайте ни помощ". Затварям.
