### ISSUE TITLE
The Bike Shed

### ISSUE THREAD

**Issue by AndrewRadev** [sanesecurityonline/sanesecurityonline#3]
Тук искам да дискутираме някакви по-дребни неща, които все пак е добре да се дискутират.

- [x] sane-security

Домейна `sanesecurity` ми беше малко мъгляв на първо четене. Прочетох го като "sanese" и после... чакай да го изпарся... ааа, "sane", "security". Може би е било заради относителната липса на кафе в системата ми, но едно тире между двете би помогнало? Also, repo-то може да е `sane-security.online`, точки са позволени.

- [x] Латиница?

Немалко хора не четат английски, или поне не достатъчно. Майка ми може да разбира тук-таме някоя дума или фраза, но домейна "sane security" няма да ѝ говори нищо. От друга страна, "razumna-sigurnost" ще се разбере от всички българи, универсално. 

Всички "умни и красиви" мразим шльокавицата, и аз я мразя, но е защото знаем английски. *Доста* бих се дразнил да преименуваме домейна на "razumna-sigurnost", но освен това обективно осъзнавам, че е по-добро решение откъм reach. Нямам добър отговор на "да го направим ли?" Заслужава си да brainstorm-нем малко алтернативни имена, белким намерим някакъв смислен компромис.

- [x] CSS

Темичката е много красива, но heading-ите са ми твърде, твърде мижави. Не много по-големи от останалия текст, и не-bold-нати. Една подчертавка за разделяне на секции също може би би подобрила нещата. Ще помисля, и може би ще направя един PR с модификации за подобряване на четимостта.

**Comment by kunev** [comment]
1. За по-добрата четимост с тирета съм много съгласен. Давах си зор да свърша повече неща за по-малко време, за да не зарежа преди някакво MVP и решението за името е леко претупано. Като цяло съм навит и на няколко домейна, които да пренасочват към един в крайна сметка. Може би този с тирето е най-добър.
1. Съгласен съм, че желанието за ползване на български термини е в разрез с тоя домейн. Шльокавицата обаче освен  (субективен?) признак на ниска култура на мен ми е и червен флаг за това, че някой е или твърде небрежен (което го прави опасен) или откровено злонамерен. Вижда ми се малко нормализация на кофти практики домейна да е на шльокавица.
Аргумента за езиковата бариера обаче е добър, не се бях сетил да мисля и за домейна и съм съгласен, че трябва да се реши. Домейн на кирилица ми се струва добро решение. `разумна-сигурност.online` изглежда адекватно, четимо е и е на български. Контраста между български и английски в домейна не е дразнещ, защото TLD-то е валидна английска дума, която е възприета чуждица.
Имам притеснения за letsencrypt, но изглежда, че [имат IDN поддръжка](https://letsencrypt.org/2016/10/21/introducing-idn-support.html).
1. За CSS-а веднага съм съгласен с две ръце. Целта ми беше да намеря възможно най-минималната тема, която просто показва текст и няма никакъв javascript. Отвъд това съм опериран от чувство за естетика и всичките ми frontend умения са нелепо закърнели. Нещата от темата могат да се override–ват файл по файл, така че давай смело.

**Comment by kunev** [comment]
До тук:
 * прекръстих хранилището
 * https://sane-security.online
 * https://разумна-сигурност.online

Може би е най-яко всички домейни в крайна сметка да водят до един и същ и това да е и хедъра и заглавието на страницата, най-добре може би всичко да е на български.

**Comment by AndrewRadev** [comment]
Добре, това ми звучи смислено. 👍

**Comment by AndrewRadev** [comment]
Ще затворя тоя issue, защото всички повдигнати въпроси ги покрихме. Ако има още дреболии за оправяне, ще отворя "The Bike Shed 2: Sone of The Bike Shed"
